### ISSUE TITLE
Error checks

### ISSUE THREAD

**Issue by strawnfaye** [strawnfaye/COP3402#10]
**fixed:**
error 1: "use = instead of :="

**need fixing:**

{
error 5: semicolon or comma missing
(it thought this was syntactically correct)
var a, b;
begin
  a:=0
end.
}

{ error 7: statement expected}

{error 8: Incorrect symbol after statement part in block}

{
error 10: semicolon between statements missing
(it gives "End expected" error instead)
var a, b;
begin
 a:= 0
 b:= 1;
end.
}

{
error 11: Undeclared identifier
(gave segmentation fault)
begin
 a:= 2;
end.
}

**Need checking:**
Errors 12 - 30

list of test inputs so far:
[error testing.txt](https://github.com/strawnfaye/COP3402/files/868963/error.testing.txt)

**Comment by shannondale** [comment]
Error 5 is for after var or const declarations, and is working. Error 10 is for after statements, and is working. NOTE: The last statement in a begin-end block does  NOT have a semicolon. It's in the grammar, not the examples. Apparently the professor confirmed this.

**Comment by shannondale** [comment]
Your test for error 7 is actually testing for an expression, which is why the program is throwing a different error. I'll update the error_test file with a new program for that, which it should work for. :)

**Comment by shannondale** [comment]
I commented out error 8 because it's the same as error 9, I think. I don't know why he gave them both to us. The symbol after the statement in block should always be a period.

**Comment by shannondale** [comment]
Fixed error 11, no more seg faults.

**Comment by shannondale** [comment]
Do you even know when error 17 is called for? I have semicolons covered, and curly brackets are not part of the language.

**Comment by shannondale** [comment]
I finished it. Can you think of any other errors to check for? I'm uploading the file on the branch.
