### ISSUE TITLE
false errors

### ISSUE THREAD

**Issue by strawnfaye** [strawnfaye/COP3402#12]
Scanf works fine for everything except for this factorial program, which is stalls on, making me believe that is the factorial program that's the problem. But just in case, I'll work through it line by line and see what's up when I get home from work at 6:15pm today.

On the simpleIf program, there's a segmentation fault only if the user enters 0, and works fine otherwise.

/*
 * SimpleIf.pl0
 * Performs a simple if condition check.
 * Output: If the input is not 0, the input is printed. Otherwise, nothing is printed and the program ends.
 */

var x;
begin
	read x;	
	if x <> 0 then
		write x
end.

On the simplewhile program, it generates an "expression cannot begin with this symbol" error.

/*
 * SimpleWhile.pl0
 * Performs a simple while loop.
 * Output: Values from start to end, decremented by 1 each time.
 */

const start = 10, finish = 0;
var current;
begin

	current := start;
	while current >= finish do
	begin
	
		write current;
		current := current - 1
		
	end

end.

**Comment by shannondale** [comment]
Fixed!!
